[project]
name = "dbt-synthea"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "dbt-duckdb>=1.9.3",
    "duckdb>=1.2.2",
    "ruamel-yaml>=0.18.10",
]
